//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envio_sms_masivos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ejecucion_automatica {
            get {
                return ((bool)(this["Ejecucion_automatica"]));
            }
            set {
                this["Ejecucion_automatica"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://35.167.149.196/ecobro/controlpagos/getPendingPaymentsToSendSMS")]
        public string WSConsultaCobros {
            get {
                return ((string)(this["WSConsultaCobros"]));
            }
            set {
                this["WSConsultaCobros"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://35.167.149.196/ecobro/controlpagos/setPendingPaymentsToSendSMSAsSent")]
        public string WSActualizarCobro {
            get {
                return ((string)(this["WSActualizarCobro"]));
            }
            set {
                this["WSActualizarCobro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public int CantidadCaracteres {
            get {
                return ((int)(this["CantidadCaracteres"]));
            }
            set {
                this["CantidadCaracteres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal SegundosSleepActualizacion {
            get {
                return ((decimal)(this["SegundosSleepActualizacion"]));
            }
            set {
                this["SegundosSleepActualizacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("|Contrato|, |Saldo|, |Recibo|, |Monto|, |Cliente|, |Celular|, |Cobrador|, |Fecha_" +
            "hora_evento|, |Estatus_cobro|, |No_cobro|, |Saldo-Monto|")]
        public string Parametros_disponibles {
            get {
                return ((string)(this["Parametros_disponibles"]));
            }
            set {
                this["Parametros_disponibles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PABS: Hemos recibido su abono por $|Monto| con folio |Recibo| para el contrato |C" +
            "ontrato| con saldo $|Saldo-Monto| el día |Fecha_hora_evento|")]
        public string Plantilla_mensaje {
            get {
                return ((string)(this["Plantilla_mensaje"]));
            }
            set {
                this["Plantilla_mensaje"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal SegundosSleepEnviarMensaje {
            get {
                return ((decimal)(this["SegundosSleepEnviarMensaje"]));
            }
            set {
                this["SegundosSleepEnviarMensaje"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Sandbox {
            get {
                return ((string)(this["Sandbox"]));
            }
            set {
                this["Sandbox"] = value;
            }
        }
    }
}
